# Generated by Django 4.0.5 on 2022-06-26 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, default='media/default.jpeg', upload_to='profiles/')),
                ('level', models.CharField(blank=True, default=100, max_length=200)),
                ('gender', models.CharField(choices=[('select', 'select'), ('male', 'male'), ('female', 'female')], default='select', max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, default='Nigeria', max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('matric_no', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_student', models.BooleanField(default=False)),
                ('verified_staff', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
