# Generated by Django 4.0.5 on 2022-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(choices=[('select', 'select'), ('CONAS', 'CONAS'), ('CBSS', 'CBSS')], default='select', max_length=100),
        ),
    ]
